name: Setup gcloud CLI with Docker auth
description: Setup the gcloud command and configure docker auth to use GCP credentials.
inputs:
  gcp-credentials-json:
    description: The Google Cloud JSON service account key to use for authentication
    required: true
runs:
  using: composite
  steps:
    - id: auth
      uses: google-github-actions/auth@v0.4.4
      with:
        credentials_json: '${{ inputs.gcp-credentials-json }}'
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ steps.auth.outputs.project_id }}
        export_default_credentials: true
    - name: Configure Google Cloud as auth provider for docker
      shell: bash
      run: gcloud --quiet auth configure-docker
